"""add product size

Revision ID: 95c74b2a8d75
Revises: 
Create Date: 2022-03-13 22:27:05.108894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c74b2a8d75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('product_size', sa.String(), nullable=False))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('store', 'product_size')
    # ### end Alembic commands ###
